DIVIDER_FPS_REDUCTION = 0.067
DETECT_MARKER = True
MARKER_SIZE = 0.6
# Define the folder path
FOLDER_CALIBRATION_CAMERA = "CALIBRATION_CAMERA_FILE"
IMAGE_CALIBRATION_PATH = "CALIB_IMAGES"
board_size = (9, 6)
MAX_FRAME_TEST = 30